### PR TITLE
Adjust auto speeds

### PR DESCRIPTION
**Pull request by linglejack06**
- refactor applyGoalSpeeds to work for teleop and auto
- change auto speeds command to setGoalSpeeds (previously a custom auto request)
- now auto and teleop always run through apply goal speeds

### CODE REVIEW

**Comment by linglejack06** [comment]
@jkleiber this is my attempt at adjusting to combine the applyGoalSpeeds. This should definitely not get merged until i get a chance to test with auto at shop (as my sim isn't showing a pose for whatever reason). but all it does is change auto to also always use applygoalspeeds (previously auto had a specific auto request which bypassed my applyGoalSpeeds method unless commanded to align.

**Comment by aidnem** [comment]
@linglejack06 We rewrote a lot of drive logic yesterday in an attempt to make auto-align and autos work better (with the robot-centric controls from path planner), so this may have been rendered obsolete. We can check in on this at shop tomorrow.

**Comment by linglejack06** [comment]
Ok, what logic was changed? Like what went wrong?Sent from my iPhoneOn Oct 20, 2024, at 12:58 PM, aidnem ***@***.***> wrote:﻿
@linglejack06 We rewrote a lot of drive logic yesterday in an attempt to make auto-align and autos work better (with the robot-centric controls from path planner), so this may have been rendered obsolete. We can check in on this at shop tomorrow.

**Comment by jkleiber** [comment]
@linglejack06 since path planner does everything in robot relative mode, we simplified the logic by going back to what we did last season with the alignment controller running on the roboRIO rather than using the Phoenix6 FieldCentricFacingAngle request type. I don't think we found a lot of success with this, though we didn't have much time to adjust things by the time we made that change.

Personally I think we should close this PR and re-baseline off of the blue ridge brawl changes on Monday.

**Pull request closed without merging**
