### PR TITLE
Bot Integration

### PR DESCRIPTION
**Pull request by linglejack06**
- fix offsets, ids, pid gains for drive
- fix intake code (still needs banner sensor added)

### CODE REVIEW

**Comment by linglejack06** [comment]
@aidnem @jkleiber We got intake working last night, it can pick up and reverse notes by driving into the note. Too much friction to pick up note at a stand still. Justin asked me to ask if you could get the aimer subsystem working before wednesday. One thing that needs to be added to it is a way to get the position of the aimer for use in intake (ie when aimer is at bottom position and aligned with intake then we can fully intake note). In the meantime, I'll try to finish the alignment for testing tomorrow and add the banner sensor support to intake. I think aimer has a banner sensor too to add. 

Ideally, we would have intake intake into holding zone, then if aimer is positioned correctly we can continue intaking, if not we would command arm to move downwards and then run intake into arm. 

Let me know how that sounds or if you want any different sort of process for intaking and aiming.

**Comment by jkleiber** [comment]
@linglejack06 can we fix the merge conflicts on this branch and get it merged sometime today? Then we can create a fresh branch for shooter/aimer integration

**Comment by jkleiber** [comment]
@linglejack06 fyi I just merged @minhnguyenbhs PR for renaming the IO interfaces so there are more conflicts now. They should be easy to resolve though

**Comment by linglejack06** [comment]
@jkleiber merged main into branch, just needs to be re reviewed and then i can merge into main

**Comment by linglejack06** [comment]
@jkleiber the renaming of intakeIOInputs to intakeInputs and all the other renaming is throwing errors on my vscode, mentioning it cant format class, but build runs fine

**Comment by linglejack06** [comment]
also, i have added a null check for the module states and module targets array. I noticed in sim that it was crashing as the very first time periodic ran there were no states yet so they were null.

**Review by jkleiber — APPROVED** [review]
ship it

**Pull request merged**
